version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: semestrovka01
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 22345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/semestrovka01
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 22345
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_HIBERNATE_DDL-AUTO: validate
      SPRING_LIQUIBASE_CHANGE-LOG: liquibase/changlelog.xml

