spring:
    web:
        resources:
            static-locations:
                - file:./uploads/
                - classpath:/static/

    application:
        name: semestrovka-course2sem2-oris

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/semestrovka01
        username: postgres
        password: 22345

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate

    liquibase:
        change-log: liquibase/changlelog.xml

    freemarker:
        expose-request-attributes: true
        enabled: true
        suffix: .ftlh
        content-type: text/html

logging:
    level:
        root: INFO
        com.example.semestrovkacourse2sem2oris: ERROR
    file:
        name: app.log

path:
    post: C:\Works\ORIS\SemestrovkaDataBase

image:
    default: default.png

app:
    upload:
        dir: uploads

api:
    image:
        token: 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

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html