<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <link href="/styles/post-create-chapters.css" rel="stylesheet">
    <link href="/styles/post-create-common.css" rel="stylesheet">
</head>
<body>
<script src="/scripts/jquery-3.6.0.min.js"></script>
<#include "post-create-navigation.ftlh">

<#include "post-create-chapters-ajax.ftlh">

<script src="/scripts/jquery-3.6.0.min.js"></script>
<script src="/scripts/post-create-navigation.js" ></script>
</body>
</html>