<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add chapter</title>
    <link rel="stylesheet" href="/styles/chapter-add.css">
    <link rel="stylesheet" href="/styles/post-create-common.css">
</head>
<body>
<script src="/scripts/jquery-3.6.0.min.js"></script>
<#include "post-create-navigation.ftlh">

<#include "post-create-chapter-add-ajax.ftlh">

<script src="/scripts/jquery-3.6.0.min.js"></script>
<script src="/scripts/post-create-navigation.js" ></script>
</body>
</html>